# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legislators', '0010_auto_20160125_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=20)),
                ('bill_type', models.CharField(choices=[('hr', 'House of Representatives'), ('hres', 'House Resolution'), ('hjres', 'House Joint Resolution'), ('hconres', 'House Concurrent Resolution'), ('s', 'Senate'), ('sres', 'Senate Resolution'), ('sjres', 'Senate Joint Resolution'), ('sconres', 'Senate Concurrent Resolution')], max_length=9)),
                ('chamber', models.CharField(choices=[('house', 'House of Representatives'), ('senate', 'Senate'), ('other', 'Other')], max_length=5)),
                ('congress', models.IntegerField()),
                ('cosponsors_count', models.IntegerField()),
                ('enacted_as', models.CharField(blank=True, max_length=50, null=True)),
                ('introduced_on', models.DateField()),
                ('last_action_at', models.DateField()),
                ('last_version_on', models.DateField()),
                ('last_vote_at', models.DateField(blank=True, null=True)),
                ('number', models.IntegerField()),
                ('official_title', models.TextField()),
                ('popular_title', models.CharField(blank=True, max_length=254, null=True)),
                ('short_title', models.CharField(blank=True, max_length=254, null=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislators.Legislator')),
            ],
        ),
    ]
