# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('hr', 'House of Representatives'), ('hres', 'House Resolution'), ('hjres', 'House Joint Resolution'), ('hconres', 'House Concurrent Resolution'), ('s', 'Senate'), ('sres', 'Senate Resolution'), ('sjres', 'Senate Joint Resolution'), ('sconres', 'Senate Concurrent Resolution')], max_length=255),
        ),
        migrations.AlterField(
            model_name='bill',
            name='chamber',
            field=models.CharField(choices=[('house', 'House of Representatives'), ('senate', 'Senate'), ('other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='bill',
            name='enacted_as',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='popular_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='short_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
