# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0002_auto_20160125_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislator',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
