# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0003_auto_20160125_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislator',
            name='leadership_role',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
