# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0008_legislator_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislator',
            name='term_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='term_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
