# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0009_auto_20160125_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislator',
            name='chamber',
            field=models.CharField(choices=[('H', 'House'), ('S', 'Senate'), ('O', 'Other')], max_length=2),
        ),
    ]
